# === PIN CONFIGURATION ===
FSR_PIN = "A2"
NEOPIXEL_PIN = "D3"

# === NEOPIXEL SETTINGS ===

# Either (R, G, B) or (R, G, B, W) depending on the color mode.\
COLOR = "(0, 255, 0)" 
# Default brightness of the LEDs. Ranges from 0.0 to 1.0
BRIGHTNESS = "0.1" 
NUM_PIXELS = 24
# Likely either GRB or GRBW. If you're not getting the expected color, try
# RGB or RGBW.
PIXEL_ORDER = "GRB" 

# === USER SETTINGS ===
PRESS_DURATION_THRESHOLD = "0.5" # Time (in seconds) the pressure plate must be held down to reset the timer.
SLEEP_TIME = "20" # Time (in fractional hours) the device will sleep before turning light back on.